export const producten = [
  [
    "P000",
    "Jonas_De_Clercq",
    "9090",
    "Melle",
    "Prachtige eetkamer",
    "Wegens verhuis is deze prachtige eetkamer te koop. Geen gebruikersschade. Als nieuw",
    750,
    "Meubelen",
    ["P000_1", "P000_2", "P000_3"],
  ],
  [
    "P001",
    "Simon_De_Witte",
    "9000",
    "Gent",
    "Eetkamer met 6 stoelen",
    "Wegens samenwonen komt deze eetkamer vrij. Werd in 2010 aangekocht.",
    "825",
    "Meubelen",
    ["P001_1", "P001_2", "P001_3"],
  ],
  [
    "P002",
    "Ilse_Van_Acker",
    "8000",
    "Brugge",
    "Eetkamer landelijke stijl met zitbankje",
    "Te koop: tafel + 3 stoelen + zitbank + dressoir + barkast",
    515,
    "Meubelen",
    ["P002_1", "P002_2", "P002_3"],
  ],
  [
    "P003",
    "Simon_De_Witte",
    "9000",
    "Gent",
    "Moderne slaapkamer",
    "Wegens samenwonen komt deze slaapkamer in zwart wit tinten vrij. Werd in 2010 aangekocht.",
    400,
    "Meubelen",
    ["P003_1", "P003_2"],
  ],
  [
    "P004",
    "Andreas_Baert",
    "2000",
    "Antwerpen",
    "Klassieke slaapkamer",
    "Zeer gerieflijke slaapkamer te koop. Af te halen in Antwerpen vanaf begin juli.",
    450,
    "Meubelen",
    ["P004_1", "P004_2"],
  ],
  [
    "P005",
    "Lieve_Van_Aelst",
    "9800",
    "Deinze",
    "Eenpersoons slaapkamer",
    "Slaapkamer met frisse look te koop voor een weggeefprijsje",
    150,
    "Meubelen",
    ["P005_1", "P005_2"],
  ],
  [
    "P006",
    "Eva_Van_Damme",
    "9700",
    "Oudenaarde",
    "Tajine te koop",
    "Tajine - 27 cm - 2 liter van LE CREUSET",
    100,
    "Keuken",
    ["P006_1", "P006_2"],
  ],
  [
    "P007",
    "Laurens_Waeterman",
    "8500",
    "Kortrijk",
    "Super de luxe grill",
    "Grill gewonnen bij tombola. Nog nieuw in verpakking. Doe een bod.",
    50,
    "Keuken",
    ["P007_1", "P007_2"],
  ],
  [
    "P008",
    "Inge_De_Meulemeester",
    "8790",
    "Waregem",
    "Pottenset",
    "Kleurrijke pottenset bestaande uit 6 potten in frisse kleuren",
    100,
    "Keuken",
    ["P008_1", "P008_2", "P008_3", "P008_4", "P008_5", "P008_6"],
  ],
  [
    "P009",
    "Iris_Wuyttens",
    "9160",
    "Lokeren",
    "Rustieke tuinset",
    "Zeer mooie rustieke tuinset met 6 stoelen. Uitstekend geschikt voor mensen die houden van landelijke stijl",
    1000,
    "Tuin",
    ["P009_1", "P009_2"],
  ],
  [
    "P010",
    "Eva_Van_Damme",
    "9700",
    "Oudenaarde",
    "Romantische tuinset",
    "Plooistoel in massief dennenhout en metaal L39 x D46 X H96 cm",
    475,
    "Tuin",
    ["P010_1", "P010_2"],
  ],
  [
    "P011",
    "Willy_Van_Wichelen",
    "9770",
    "Kruisem",
    "Box voor tuinkussens",
    "Tuinkussenbox in PVC B 120 x D 52 x H 60 cm",
    50,
    "Tuin",
    ["P011_1"],
  ],
  [
    "P012",
    "Nathalie_Everts",
    "9100",
    "Sint Niklaas",
    "Tuinspot",
    "Tuinspot in grijze en in zwarte PVC 1 x 450W",
    5,
    "Tuin",
    ["P012_1", "P012_2"],
  ],
  [
    "P013",
    "Johan_Allaert",
    "2550",
    "Kontich",
    "Tuinset",
    "Heel mooie tuinset bestaande uit tafel en 8 rieten stoel. Weggeefprijs",
    575,
    "Tuin",
    ["P013_1", "P013_2", "P013_3"],
  ],
  [
    "P014",
    "Linde_Dejaegher",
    "8550",
    "Zwevegem",
    "Houten tuinset met  6 stoelen",
    "Omdat we verhuizen naar een appartement kunnen we onze tuinset niet meenemen.",
    365,
    "Tuin",
    ["P014_1", "P014_2", "P014_3"],
  ],
  [
    "P015",
    "Mathilde_De_Laet",
    "9850",
    "Merendree",
    "Houdertjes voor theelichtjes",
    "Houdertjes voor theelichtjes. Als je meerdere koopt, zakt de prijs wel",
    5,
    "Tuin",
    ["P015_1", "P015_2"],
  ],
];
